build_now:              'YES'
download_base_url:      'http://pg.savorydeviate.com/download/'
appcast_basefolder:     '~/Documents/9-Development/pocketgnome/1.5/'
appcast_xml_name:       'appcast.xml'
keychain_privkey_name:  'Sparkle Private Key 1'
css_file_name:          'rnotes.css'

